esphome:
  name: rika-stove

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

# At least one time source is required
time:
  - platform: homeassistant
    id: homeassistant_time

logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

uart:
  id: rika_uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 38400

rika_gsm:
  id: ria_gsm_component_1
  pin: "1234"